/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linecounterapp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.File;

class AppTest {
    @Test void appHasAGreeting() {    	
        App classUnderTest = new App();
    }
}
